### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: performance is not defined | HELP on ERROR 

### ISSUE THREAD

**Issue by ChitinNature** [hashlips-lab/hashlips-lab#6]
When I extract the template to a fresh file on the desktop, then open in Visual Code, ran Yarn. 

Then I removed the Solana stuff. Then Ran node index.js

I get this error

![image](https://user-images.githubusercontent.com/124227651/224468864-f064018b-08b9-4fb5-8d28-fd02a8b2f546.png)

In the error description it says to add this code to terminate the node process on unhandled promise rejection, so I did as so:

> node --unhandled-restrictions=strict index.js

![image](https://user-images.githubusercontent.com/124227651/224468717-131d1c4d-36e4-478c-8c78-f111c6b579cd.png)

I watched both videos a couple times now, just reaching out to see if there's a solution.

**Comment by liarco** [comment]
Hi @ChitinNature, thank you for reporting this.
I guess you are using NodeJS version 14 as the `performance` global variable was introduced in version 16. I pushed a quick fix to the repo and I will publish a new alpha version after a few tests.

I can't guarantee we are gonna support Node 14 with our stable release since it's pretty old, but it's good to keep backward compatibility as much as possible atm.

I wish you a great day, please consider supporting us by joining the [Open Devs Crew](https://opendevs.io), this gives access to the dev team in case you need support for anything that is not a bug.

**Comment by ChitinNature** [comment]
Oh man thanks for replying!

Did you see I found the fix, I should have posted it here as well! Its on
YouTube comments haha
